### ISSUE TITLE
Unable to get this to work

### ISSUE THREAD

**Issue by kershnerd** [MengTo/react-native-for-designers#6]
I have tried this a ton of different ways and I am unable to get this to run in expo.

Doing a git clone and a yarn install, I get a bunch of errors relating to a make build error with gyp.

```22 warnings and 11 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=5\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=5 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command \"/usr/local/bin/node\" \"/Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/jeff/projects/personal/react-native-for-designers/node_modules/fsevents
node-pre-gyp ERR! node -v v12.14.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok```

If I ignore that and do a `yarn start`, I get the following error on my iPhone:

```The experience you requested uses Expo SDK v(null) but this copy of Expo client requires at least v33.0.0.  The author should update their experience to a newer Expo SDK version```

If I try to update (`expo update 34.0.0`), then I get the same build errors as above.  When running, I start a chain of missing dependencies:

``` Unable to resolve module 'react-native-svg'```

I am unable to get this to run.  Please help!

**Comment by oldevelopment** [comment]
I had the same issue. Running "npm i react-native-svg --save" & "npm i" fixed it.
